{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-ndk",
    "version": "6.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.18.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-ndk-6.18.1.aar",
          "url": "sentry-android-ndk-6.18.1.aar",
          "size": 1615959,
          "sha512": "b48a97d4138517684d005b567aa5405d853b607449b8bb5ff7bf803553eedc5e88238d1bb7552a8b29316393fe0d0b6c3bc5b9d2d4b73c964656481531e62ab7",
          "sha256": "1fa798e916937a91f6828b0703cf7acc938bb4fbc3d17c707578c76b2c7ad845",
          "sha1": "e565d15ebba936c267079ddf8046389522d3f7f9",
          "md5": "8108ac4eceb55f6a15f93a147cbbc52f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.18.1"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-ndk-6.18.1.aar",
          "url": "sentry-android-ndk-6.18.1.aar",
          "size": 1615959,
          "sha512": "b48a97d4138517684d005b567aa5405d853b607449b8bb5ff7bf803553eedc5e88238d1bb7552a8b29316393fe0d0b6c3bc5b9d2d4b73c964656481531e62ab7",
          "sha256": "1fa798e916937a91f6828b0703cf7acc938bb4fbc3d17c707578c76b2c7ad845",
          "sha1": "e565d15ebba936c267079ddf8046389522d3f7f9",
          "md5": "8108ac4eceb55f6a15f93a147cbbc52f"
        }
      ]
    }
  ]
}
