{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-core",
    "version": "6.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-core-6.24.0.aar",
          "url": "sentry-android-core-6.24.0.aar",
          "size": 218975,
          "sha512": "c50d96afd9bc1a7b4308c06de1a324ea3e04c4e8bc38bae38467ba1f8c4e7152f7f35b0b1fb06261f6b02abc106da9640a098b6463c825dc6cb17b627e2b1f62",
          "sha256": "8332b69d94ee420720c115339e52daceb40a3dc1f442c2c7e91aea17be353b81",
          "sha1": "2c80222d3808689a1d04e6bc90845eb15dcfb30b",
          "md5": "7aad3d2f96503afe6697605666e2d24f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-core-6.24.0.aar",
          "url": "sentry-android-core-6.24.0.aar",
          "size": 218975,
          "sha512": "c50d96afd9bc1a7b4308c06de1a324ea3e04c4e8bc38bae38467ba1f8c4e7152f7f35b0b1fb06261f6b02abc106da9640a098b6463c825dc6cb17b627e2b1f62",
          "sha256": "8332b69d94ee420720c115339e52daceb40a3dc1f442c2c7e91aea17be353b81",
          "sha1": "2c80222d3808689a1d04e6bc90845eb15dcfb30b",
          "md5": "7aad3d2f96503afe6697605666e2d24f"
        }
      ]
    }
  ]
}
