{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android",
    "version": "6.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.24.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-ndk",
          "version": {
            "requires": "6.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-6.24.0.aar",
          "url": "sentry-android-6.24.0.aar",
          "size": 1345,
          "sha512": "9cb4465ae5951e27542fe4abc16cabda4dec9d487cc25141712794499d44dd663a838e53fd681a0cc58a27747052b45216ad76967e8083fe1e3468c008311787",
          "sha256": "5c81357cfad1f2706df758a5733eab9edb04081dcc8e1e2787336d936319c8b6",
          "sha1": "fc3b81be6d2b72f218e4f380e1e659e08ee610de",
          "md5": "4ad49527a0ffdc4a7c354c70ff46a0c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.24.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-ndk",
          "version": {
            "requires": "6.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-6.24.0.aar",
          "url": "sentry-android-6.24.0.aar",
          "size": 1345,
          "sha512": "9cb4465ae5951e27542fe4abc16cabda4dec9d487cc25141712794499d44dd663a838e53fd681a0cc58a27747052b45216ad76967e8083fe1e3468c008311787",
          "sha256": "5c81357cfad1f2706df758a5733eab9edb04081dcc8e1e2787336d936319c8b6",
          "sha1": "fc3b81be6d2b72f218e4f380e1e659e08ee610de",
          "md5": "4ad49527a0ffdc4a7c354c70ff46a0c0"
        }
      ]
    }
  ]
}
