{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-ndk",
    "version": "6.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.20.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-ndk-6.20.0.aar",
          "url": "sentry-android-ndk-6.20.0.aar",
          "size": 1635460,
          "sha512": "2ddd6737868b6ddc1bb6b89d86d272eebc4a839adff317fa2ff5f515dc9112f37e55bf4283874e1c2a66923a997bc91d288e679298bc06c8866355af563656e4",
          "sha256": "d7ce1c7ed09c409efd3bfa8a9e06aff730f07016bbb13df81d15290902f87a10",
          "sha1": "55a022b33e17808bc22711e7d68425323b7add83",
          "md5": "beaff84c67c204905c2a8bbc8a1d6437"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.20.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-ndk-6.20.0.aar",
          "url": "sentry-android-ndk-6.20.0.aar",
          "size": 1635460,
          "sha512": "2ddd6737868b6ddc1bb6b89d86d272eebc4a839adff317fa2ff5f515dc9112f37e55bf4283874e1c2a66923a997bc91d288e679298bc06c8866355af563656e4",
          "sha256": "d7ce1c7ed09c409efd3bfa8a9e06aff730f07016bbb13df81d15290902f87a10",
          "sha1": "55a022b33e17808bc22711e7d68425323b7add83",
          "md5": "beaff84c67c204905c2a8bbc8a1d6437"
        }
      ]
    }
  ]
}
