{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry",
    "version": "6.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sentry-6.21.0.jar",
          "url": "sentry-6.21.0.jar",
          "size": 702712,
          "sha512": "04ef3b245aa9357fada5b1118781809266c31594c87e1e637f88cb04e7c63445db9f553631911d2ec8ccdb650503c4c55cffd0f5f11efa5cbf5a685f37fd2362",
          "sha256": "1b950f798fa82cec165c47fffc11408580c10c24f3021c1a386ffdd1605cef7c",
          "sha1": "58817495681c6507b1b34efcee62110297bdcd9f",
          "md5": "b7720e4a3d65cef9a8b4cb79317c72d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sentry-6.21.0.jar",
          "url": "sentry-6.21.0.jar",
          "size": 702712,
          "sha512": "04ef3b245aa9357fada5b1118781809266c31594c87e1e637f88cb04e7c63445db9f553631911d2ec8ccdb650503c4c55cffd0f5f11efa5cbf5a685f37fd2362",
          "sha256": "1b950f798fa82cec165c47fffc11408580c10c24f3021c1a386ffdd1605cef7c",
          "sha1": "58817495681c6507b1b34efcee62110297bdcd9f",
          "md5": "b7720e4a3d65cef9a8b4cb79317c72d6"
        }
      ]
    }
  ]
}
