{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry",
    "version": "6.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sentry-6.24.0.jar",
          "url": "sentry-6.24.0.jar",
          "size": 704689,
          "sha512": "a0d136c402cf976ccac4cc1852f0c3b31618781059b0b3aacb78ddd93c4d6b893fae6e196dea6879d5636949efda82d7b222d58fd1f5b36f2e5fafc0eebdc374",
          "sha256": "7c439884249694486403ecea1df47f322ec29707d13f098b3274a889ce458995",
          "sha1": "2e226b576043d4c083abbacf0fddfda165e312e1",
          "md5": "5fce1d0ea26c5e7cd56683f78e1e91c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sentry-6.24.0.jar",
          "url": "sentry-6.24.0.jar",
          "size": 704689,
          "sha512": "a0d136c402cf976ccac4cc1852f0c3b31618781059b0b3aacb78ddd93c4d6b893fae6e196dea6879d5636949efda82d7b222d58fd1f5b36f2e5fafc0eebdc374",
          "sha256": "7c439884249694486403ecea1df47f322ec29707d13f098b3274a889ce458995",
          "sha1": "2e226b576043d4c083abbacf0fddfda165e312e1",
          "md5": "5fce1d0ea26c5e7cd56683f78e1e91c7"
        }
      ]
    }
  ]
}
