{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-ndk",
    "version": "6.21.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.21.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-ndk-6.21.0.aar",
          "url": "sentry-android-ndk-6.21.0.aar",
          "size": 1635462,
          "sha512": "271ea720fde2f69cbd537f475d0c52195934c1d8d5304f45282d528793fecc02d33a7d9af6c63159a4f480e70a92cda96d672178d075c1eee22eadbad785c2fd",
          "sha256": "c661d94caa2bc183b9c8b983a5ca6984237f3bc9381ff738c48d11f2324ac8f3",
          "sha1": "a3d2c5a2872515ea4dc0b1d38407174b6ce26c57",
          "md5": "0e61dfa82654a031cae1857f49342beb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.21.0"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android-core",
          "version": {
            "requires": "6.21.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-ndk-6.21.0.aar",
          "url": "sentry-android-ndk-6.21.0.aar",
          "size": 1635462,
          "sha512": "271ea720fde2f69cbd537f475d0c52195934c1d8d5304f45282d528793fecc02d33a7d9af6c63159a4f480e70a92cda96d672178d075c1eee22eadbad785c2fd",
          "sha256": "c661d94caa2bc183b9c8b983a5ca6984237f3bc9381ff738c48d11f2324ac8f3",
          "sha1": "a3d2c5a2872515ea4dc0b1d38407174b6ce26c57",
          "md5": "0e61dfa82654a031cae1857f49342beb"
        }
      ]
    }
  ]
}
