{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-core",
    "version": "6.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-core-6.18.1.aar",
          "url": "sentry-android-core-6.18.1.aar",
          "size": 211838,
          "sha512": "76af929fea279a94b61af316058a6f0e0eae2e397eac8d4f71434f845f7750e5e5693f6561aa78833117ab91b57784fb016a5eb34ab94a281b57dbe5b65ec86b",
          "sha256": "1b96b261b3fbe3a3a3b55eaf9fdb35eb6a857ea64ecc4ac1790583f383651a77",
          "sha1": "ca5f9574184fd09b4a456044b7603369e2c0fa25",
          "md5": "9b1f004ef38187a5b2e59aa38887bdad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-core-6.18.1.aar",
          "url": "sentry-android-core-6.18.1.aar",
          "size": 211838,
          "sha512": "76af929fea279a94b61af316058a6f0e0eae2e397eac8d4f71434f845f7750e5e5693f6561aa78833117ab91b57784fb016a5eb34ab94a281b57dbe5b65ec86b",
          "sha256": "1b96b261b3fbe3a3a3b55eaf9fdb35eb6a857ea64ecc4ac1790583f383651a77",
          "sha1": "ca5f9574184fd09b4a456044b7603369e2c0fa25",
          "md5": "9b1f004ef38187a5b2e59aa38887bdad"
        }
      ]
    }
  ]
}
