{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-core",
    "version": "6.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-core-6.20.0.aar",
          "url": "sentry-android-core-6.20.0.aar",
          "size": 215017,
          "sha512": "84fc6849966feb419ce70e6d4297ee94693952a2df362e1787f49917f3263fbaf75faa2b07a49dd4f127e746619a8cae2c43da9e5145ee6047c34b99af6aedba",
          "sha256": "43c96a0a744c27fc6788818a4456f5242bd74eb75ab2572e282a90d601d87e28",
          "sha1": "833896a1e5a2d87fbbcc59f362e7fcc5e20578ee",
          "md5": "b0456b2de59a4be0afb15691cc31c4b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "6.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-core-6.20.0.aar",
          "url": "sentry-android-core-6.20.0.aar",
          "size": 215017,
          "sha512": "84fc6849966feb419ce70e6d4297ee94693952a2df362e1787f49917f3263fbaf75faa2b07a49dd4f127e746619a8cae2c43da9e5145ee6047c34b99af6aedba",
          "sha256": "43c96a0a744c27fc6788818a4456f5242bd74eb75ab2572e282a90d601d87e28",
          "sha1": "833896a1e5a2d87fbbcc59f362e7fcc5e20578ee",
          "md5": "b0456b2de59a4be0afb15691cc31c4b2"
        }
      ]
    }
  ]
}
